name: simulationS25
channels:
  - conda-forge
dependencies:
  - python=3.11
  - colour>=0.1.5
  - jpype1>=1.4
  - jupyterlab
  - line_profiler>=4.0
  - matplotlib>=3.7
  - numpy>=1.24
  - pandas>=1.5
  - pint>=0.22
  - pillow>=9.5
  - pip
  - pylab
  - scipy>=1.10
  - shapely>=2.0
  - trimesh>=3.23
  - pip:
      - py5[jupyter]